### ISSUE TITLE
Support for MySQL database

### ISSUE THREAD

**Issue by kevin1193** [mayajs/sql#1]
## 📝 Description

Create a MySql Wrapper for MayaJS.

### Functions
- [x] Sql
- [x] Query
- [x] CreateDatabase
- [x] CreateTable
- [x] Select
- [x] Insert
- [x] Update
- [x] Delete

### Sql
Create a MySql Database settings that can be consume on AppModule.

### Query
A general function for executing SQL Queries.

### CreateDatabase
Create a MySql Database.

### CreateTable
Create a MySql Table.

### Select
A function for selecting data in database.

### Insert
A function for inserting data in database.

### Update
A function for updating data in database.

### Delete
A function for deleting data in database.

**Comment by Mackignacio** [comment]
Already implemented on V0.1.1
