### ISSUE TITLE
Adding another option for columns to be selected in the select function

### ISSUE THREAD

**Issue by Migsmags** [mayajs/sql#2]
## 📝 Description
Hello Sir,

Requesting to have a separate option for the column/s to be selected for the select query.

It is a bit vague in the documentation because the option 'table' is where you're going to specify columns names and it also contains the keyword 'FROM'.

I was hoping to see something like this.

// Select OPTIONS
const options = {
  columns : (array of columns),  
  table: "table-name",
  ...
};

where columns has a default value of '*' if it is not specified. 

Thanks

**Comment by Mackignacio** [comment]
The columns property will be `OPTIONAL` with default value of `*`. We will also remove the `FROM` keyword. It will automatically added to the query inside the `Select` function.

**Comment by Mackignacio** [comment]
Fix #4
